### ISSUE TITLE
Instagram erro

### ISSUE THREAD

**Issue by develogo** [elvisyjlin/media-scraper#17]
S C:\Users\Ego Brain\Documents\Python\ScrapingSocial\media-scraper> python  m-scraper.py rq instagram aeso_barrosmelo
Namespace(credential_file=None, early_stop=False, keywords=['aeso_barrosmelo'], save_path=None)
Instagramer Task: aeso_barrosmelo
Traceback (most recent call last):
  File "m-scraper.py", line 36, in <module>
    scraper.run(sys.argv[3:])
  File "C:\Users\Ego Brain\Documents\Python\ScrapingSocial\media-scraper\m_scraper\rq\downloader.py", line 82, in run
    self.crawl(keyword, args.early_stop)
  File "C:\Users\Ego Brain\Documents\Python\ScrapingSocial\media-scraper\m_scraper\rq\instagramer.py", line 46, in crawl
    tasks, end_cursor, has_next, length, user_id, rhx_gis, csrf_token = get_first_page(username)
  File "C:\Users\Ego Brain\Documents\Python\ScrapingSocial\media-scraper\m_scraper\rq\utils\instagram.py", line 52, in get_first_page
    rhx_gis = shared_data['rhx_gis']
KeyError: 'rhx_gis'
PS C:\Users\Ego Brain\Documents\Python\ScrapingSocial\media-scraper>

**Comment by coldjeans121** [comment]
edit
rhx_gis = shared_data['rhx_gis']
to
rhx_gis = None
